= moment-dayinfo ReadMe
:project-name: Typescript Calendar class implemented as a moment.js plugin
:project-handle: moment-calendarday
:project-uri: https://github.com/ChrLipp/{project-handle}
:project-repo-uri: {project-uri}
:project-issues-uri: {project-repo-uri}/issues

== What is it?
A http://momentjs.com/[moment.js] plugin which allows to config and access calendar day
information. I wanted to name the plugin `moment-calender`, a name which is already taken.
Therefor I had to change the name to `{project-handle}`.

This project is the successor of the project
https://github.com/ChrLipp/calendar-standalone[calendar-standalone]. Any further development
will be done in this project.

== Configuration
A calendar day is described with the class CalenderDayEntry.
Currently it has just two properties:

- name, the name of the day
- isFeastDay, a boolean property which defines if the day is a feast day

The initialisation of a calendar year is done with a JSON structure, defined in ConfigDays.
The advantage of the given implementation is that the config is year independent, so there is no
need to adapt the config every year.

For some config examples have a look at the unit tests `src/test/*ConfigSpec.ts

== Usage

== Rework needed

